((_m) => {

  const sql = [
    {
      outputfile: 'TABLES.json',
      sql: `SELECT OWNER, OBJECT_NAME, OBJECT_TYPE FROM ALL_OBJECTS WHERE OWNER='[[owner]]' ORDER BY OBJECT_TYPE, OBJECT_NAME`,
    },
    {
      outputfile: 'COLUMNS.json',
      sql: `SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, DATA_DEFAULT FROM ALL_TAB_COLUMNS WHERE OWNER='[[owner]]' ORDER BY TABLE_NAME, COLUMN_NAME`,
    },
    {
      outputfile: 'CONSTRAINTS.json',
      sql: `SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, STATUS FROM ALL_CONSTRAINTS WHERE OWNER='[[owner]]' ORDER BY TABLE_NAME, CONSTRAINT_TYPE`,
    },
    {
      outputfile: 'INDEX_TABLESPACES.json',
      sql: `SELECT OWNER, INDEX_NAME, TABLESPACE_NAME, INDEX_TYPE, TABLE_OWNER, TABLE_NAME, UNIQUENESS FROM ALL_INDEXES WHERE OWNER='[[owner]]'`,
    }
  ];

  _m.exports = {
    PLSQL: sql,
  };

})(module);

