INSERT INTO EQU_DEV.GLOBE(ID, NAME, DESCRIPTION, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
  VALUES(1, 'EARTH', 'this is our planet', SYSDATE, 'USER1',  SYSDATE, 'USER1');

/
COMMIT;

INSERT INTO EQU_TST.GLOBE(ID, NAME, DESCRIPTION, CREATED_ON, CREATED_BY)
  VALUES(1, 'EARTH', '', SYSDATE, 'USER1');

/
COMMIT;