CREATE TABLE EQU_TST.GLOBE (
  ID NUMBER(4) PRIMARY KEY,
  NAME VARCHAR2(15) NOT NULL,
  DESCRIPTION VARCHAR2(100) NULL,
  CREATED_ON DATE DEFAULT (SYSDATE),
  CREATED_BY VARCHAR2(10) NOT NULL
  ) TABLESPACE EQU_TBS_DATA;



  ----------------------------------------------

CREATE TABLE EQU_DEV.GLOBE (
  ID NUMBER PRIMARY KEY USING INDEX TABLESPACE EQU_TBS_IDX,
  NAME VARCHAR2(15) NOT NULL,
  DESCRIPTION VARCHAR2(100) NULL,
  CREATED_ON DATE DEFAULT (SYSDATE),
  CREATED_BY VARCHAR2(10) NOT NULL,
  UPDATED_ON DATE DEFAULT (SYSDATE),
  UPDATED_BY VARCHAR2(10) NOT NULL
  ) TABLESPACE EQU_TBS_DATA;

CREATE TABLE EQU_DEV.COUNTRY (
  ID NUMBER PRIMARY KEY  USING INDEX TABLESPACE EQU_TBS_IDX,
  NAME VARCHAR2(20),
  GLOBE_ID NUMBER
);


---------------------------------------------------------------
GRANT SELECT ON EQU_DEV.GLOBE TO EQU_TST;
GRANT INSERT ON EQU_DEV.GLOBE TO EQU_TST;
GRANT DELETE ON EQU_DEV.GLOBE TO EQU_TST;
GRANT UPDATE ON EQU_DEV.GLOBE TO EQU_TST;
GRANT REFERENCES ON EQU_DEV.GLOBE TO EQU_TST;
GRANT ALTER ON EQU_DEV.GLOBE TO EQU_TST;
GRANT INDEX ON EQU_DEV.GLOBE TO EQU_TST;
