CREATE VIEW GLOBE_COUNTRY
	AS SELECT
	  G.ID AS GLOBE_ID,  G.NAME AS GLOBE_NAME,
	  C.ID AS COUTRY_ID, C.NAME AS COUNTRY_NAME
	FROM GLOBE G
	INNER JOIN COUNTRY C ON C.GLOBE_ID = G.ID;


CREATE VIEW COUNTRY_STATE
	AS SELECT
	  S.ID AS STATE_ID, S.NAME AS STATE_NAME,
	  C.ID AS COUTRY_ID,  C.NAME AS COUNTRY_NAME
	FROM COUNTRY C
	INNER JOIN STATE S ON S.COUNTRY_ID = C.ID;
