SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, DATA_DEFAULT FROM ALL_TAB_COLUMNS WHERE OWNER='EQU_DEV' ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT * FROM SYS.USER_TAB_COLUMNS C
INNER JOIN
WHERE TABLE_NAME='GLOBE' ORDER BY COLUMN_NAME
;

SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='GLOBE' ;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='COUNTRY' ;
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, STATUS  FROM ALL_CONSTRAINTS WHERE OWNER='EQU_DEV' ORDER BY TABLE_NAME, CONSTRAINT_TYPE;



SELECT OWNER, OBJECT_NAME, OBJECT_TYPE FROM ALL_OBJECTS WHERE OWNER='EQU_DEV' ORDER BY OBJECT_TYPE, OBJECT_NAME;
