SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, DATA_DEFAULT FROM ALL_TAB_COLUMNS WHERE OWNER='EQU_DEV' ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT * FROM SYS.USER_TAB_COLUMNS C
INNER JOIN
WHERE TABLE_NAME='GLOBE' ORDER BY COLUMN_NAME
;

SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='GLOBE' ;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='COUNTRY' ;
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, STATUS
FROM ALL_CONSTRAINTS WHERE OWNER='EQU_DEV' ORDER BY TABLE_NAME, CONSTRAINT_TYPE;



SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
FROM ALL_OBJECTS WHERE OWNER='EQU_DEV' ORDER BY OBJECT_TYPE, OBJECT_NAME;


GRANT SELECT ON EQU_DEV.GLOBE TO EQU_TST;
GRANT INSERT ON EQU_DEV.GLOBE TO EQU_TST;
GRANT DELETE ON EQU_DEV.GLOBE TO EQU_TST;
GRANT UPDATE ON EQU_DEV.GLOBE TO EQU_TST;
GRANT REFERENCES ON EQU_DEV.GLOBE TO EQU_TST;
GRANT ALTER ON EQU_DEV.GLOBE TO EQU_TST;
GRANT INDEX ON EQU_DEV.GLOBE TO EQU_TST;

SELECT OWNER, TABLE_NAME, GRANTOR, GRANTEE, SELECT_PRIV, INSERT_PRIV, DELETE_PRIV, UPDATE_PRIV, REFERENCES_PRIV, ALTER_PRIV, INDEX_PRIV
FROM TABLE_PRIVILEGES
WHERE OWNER = 'EQU_DEV';

SELECT T.OWNER, T.NAME, T.TYPE, TO_CLOB(DBMS_METADATA.GET_DDL(T.TYPE, T.NAME)) AS TEXT
  FROM (SELECT DISTINCT OWNER, NAME, TYPE FROM ALL_SOURCE WHERE OWNER='EQU_DEV') T ORDER BY T.NAME, T.TYPE;
